# Generated by Django 6.0.3 on 2026-03-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "pessoas",
            "0002_categoria_cliente_ingrediente_membro_personaltrainer_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="cliente",
        ),
        migrations.RemoveField(
            model_name="receita",
            name="ingredientes",
        ),
        migrations.RemoveField(
            model_name="itempedido",
            name="pedido",
        ),
        migrations.RemoveField(
            model_name="itempedido",
            name="produto",
        ),
        migrations.RemoveField(
            model_name="sessaotreino",
            name="membro",
        ),
        migrations.RemoveField(
            model_name="sessaotreino",
            name="personal_trainer",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="turmas",
        ),
        migrations.RemoveField(
            model_name="receita",
            name="favoritada_por",
        ),
        migrations.AlterUniqueTogether(
            name="sessaotreino",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="Aluno",
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
        migrations.DeleteModel(
            name="Ingrediente",
        ),
        migrations.DeleteModel(
            name="Pedido",
        ),
        migrations.DeleteModel(
            name="ItemPedido",
        ),
        migrations.DeleteModel(
            name="Produto",
        ),
        migrations.DeleteModel(
            name="Membro",
        ),
        migrations.DeleteModel(
            name="PersonalTrainer",
        ),
        migrations.DeleteModel(
            name="SessaoTreino",
        ),
        migrations.DeleteModel(
            name="Professor",
        ),
        migrations.DeleteModel(
            name="Turma",
        ),
        migrations.DeleteModel(
            name="Receita",
        ),
        migrations.DeleteModel(
            name="Utilizador",
        ),
    ]
