# Generated by Django 6.0.3 on 2026-03-31 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("licenciatura", "0001_initial"),
        ("tecnologias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("conceitos_aplicados", models.TextField()),
                ("imagem", models.ImageField(blank=True, upload_to="projetos/")),
                ("video_demo", models.URLField(blank=True)),
                ("repositorio_github", models.URLField(blank=True)),
                ("ano", models.IntegerField()),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="tecnologias.tecnologia"
                    ),
                ),
                (
                    "unidade_curricular",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos",
                        to="licenciatura.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
