# Generated by Django 6.0.3 on 2026-03-31 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entidade",
                    models.CharField(
                        choices=[
                            ("licenciatura", "Licenciatura"),
                            ("unidade_curricular", "Unidade Curricular"),
                            ("projeto", "Projeto"),
                            ("tecnologia", "Tecnologia"),
                            ("tfc", "TFC"),
                            ("competencia", "Competência"),
                            ("formacao", "Formação"),
                            ("makingof", "Making Of"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("data", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ErroCorrecao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao_erro", models.TextField()),
                ("correcao_aplicada", models.TextField()),
                ("data", models.DateField()),
                (
                    "making_of",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="erros",
                        to="makingof.makingof",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DecisaoModelacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("justificacao", models.TextField()),
                (
                    "making_of",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisoes",
                        to="makingof.makingof",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistoPapel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=200)),
                ("imagem", models.ImageField(upload_to="makingof/papel/")),
                (
                    "making_of",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registos_papel",
                        to="makingof.makingof",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsoIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ferramenta", models.CharField(max_length=100)),
                ("descricao_uso", models.TextField()),
                ("contribuicao", models.TextField()),
                ("data", models.DateField()),
                (
                    "making_of",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usos_ia",
                        to="makingof.makingof",
                    ),
                ),
            ],
        ),
    ]
