# Generated by Django 6.0.3 on 2026-03-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tecnologias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("autor", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("repositorio", models.URLField(blank=True)),
                ("destaque", models.BooleanField(default=False)),
                (
                    "classificacao",
                    models.IntegerField(
                        choices=[
                            (1, "★"),
                            (2, "★★"),
                            (3, "★★★"),
                            (4, "★★★★"),
                            (5, "★★★★★"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="tfcs", to="tecnologias.tecnologia"
                    ),
                ),
            ],
        ),
    ]
