# Generated by Django 6.0.3 on 2026-04-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tfcs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tfc",
            name="ano",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="repositorio",
        ),
        migrations.AddField(
            model_name="tfc",
            name="autores",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="tfc",
            name="imagem",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tfc",
            name="licenciatura",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="tfc",
            name="link_pdf",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tfc",
            name="orientador",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
