# Generated by Django 6.0.3 on 2026-03-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projetos", "0001_initial"),
        ("tecnologias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("tecnica", "Técnica"),
                            ("soft", "Soft Skill"),
                            ("linguistica", "Linguística"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "nivel",
                    models.IntegerField(
                        choices=[(1, "Básico"), (2, "Intermédio"), (3, "Avançado")],
                        default=1,
                    ),
                ),
                (
                    "projetos",
                    models.ManyToManyField(
                        blank=True, related_name="competencias", to="projetos.projeto"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="competencias",
                        to="tecnologias.tecnologia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conquista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("premio", "Prémio"),
                            ("hackathon", "Hackathon"),
                            ("mencao", "Menção Honrosa"),
                            ("participacao", "Participação"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("data", models.DateField()),
                ("entidade_organizadora", models.CharField(max_length=100)),
                ("imagem", models.ImageField(blank=True, upload_to="conquistas/")),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="conquistas",
                        to="competencias.competencia",
                    ),
                ),
            ],
        ),
    ]
