# Generated by Django 6.0.3 on 2026-04-21 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("tecnica", "Técnica"),
                            ("soft", "Soft Skill"),
                            ("linguistica", "Linguística"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "nivel",
                    models.IntegerField(
                        choices=[(1, "Básico"), (2, "Intermédio"), (3, "Avançado")],
                        default=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, unique=True)),
                ("pagina_lusofona", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sigla", models.CharField(max_length=10)),
                ("ects_totais", models.IntegerField()),
                ("duracao_anos", models.IntegerField()),
                (
                    "regime",
                    models.CharField(
                        choices=[
                            ("presencial", "Presencial"),
                            ("elearning", "E-Learning"),
                            ("misto", "Misto"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entidade",
                    models.CharField(
                        choices=[
                            ("licenciatura", "Licenciatura"),
                            ("unidade_curricular", "Unidade Curricular"),
                            ("projeto", "Projeto"),
                            ("tecnologia", "Tecnologia"),
                            ("tfc", "TFC"),
                            ("competencia", "Competência"),
                            ("formacao", "Formação"),
                            ("makingof", "Making Of"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("data", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("conceitos_aplicados", models.TextField()),
                ("imagem", models.ImageField(blank=True, upload_to="projetos/")),
                ("video_demo", models.URLField(blank=True)),
                ("repositorio_github", models.URLField(blank=True)),
                ("ano", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("linguagem", "Linguagem"),
                            ("framework", "Framework"),
                            ("base_dados", "Base de Dados"),
                            ("devops", "DevOps"),
                            ("ferramenta", "Ferramenta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("logo", models.ImageField(blank=True, upload_to="tecnologias/")),
                ("website", models.URLField(blank=True)),
                (
                    "nivel_interesse",
                    models.IntegerField(
                        choices=[
                            (1, "Iniciante"),
                            (2, "Básico"),
                            (3, "Intermédio"),
                            (4, "Avançado"),
                            (5, "Especialista"),
                        ],
                        default=3,
                    ),
                ),
                ("destaque", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Conquista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("premio", "Prémio"),
                            ("hackathon", "Hackathon"),
                            ("mencao", "Menção Honrosa"),
                            ("participacao", "Participação"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("data", models.DateField()),
                ("entidade_organizadora", models.CharField(max_length=100)),
                ("imagem", models.ImageField(blank=True, upload_to="conquistas/")),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="conquistas",
                        to="portfolio.competencia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("instituicao", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("academica", "Académica"),
                            ("curso", "Curso Online"),
                            ("certificacao", "Certificação"),
                            ("workshop", "Workshop"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("descricao", models.TextField(blank=True)),
                (
                    "certificado",
                    models.FileField(blank=True, upload_to="certificados/"),
                ),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="formacoes", to="portfolio.competencia"
                    ),
                ),
            ],
            options={
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="ErroCorrecao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao_erro", models.TextField()),
                ("correcao_aplicada", models.TextField()),
                ("data", models.DateField()),
                (
                    "making_of",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="erros",
                        to="portfolio.makingof",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DecisaoModelacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("justificacao", models.TextField()),
                (
                    "making_of",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisoes",
                        to="portfolio.makingof",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="competencia",
            name="projetos",
            field=models.ManyToManyField(
                blank=True, related_name="competencias", to="portfolio.projeto"
            ),
        ),
        migrations.CreateModel(
            name="RegistoPapel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=200)),
                ("imagem", models.ImageField(upload_to="makingof/papel/")),
                (
                    "making_of",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registos_papel",
                        to="portfolio.makingof",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True, related_name="projetos", to="portfolio.tecnologia"
            ),
        ),
        migrations.AddField(
            model_name="competencia",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True, related_name="competencias", to="portfolio.tecnologia"
            ),
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autores", models.CharField(default="", max_length=200)),
                (
                    "orientador",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "licenciatura",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("link_pdf", models.URLField(blank=True, default="")),
                ("imagem", models.URLField(blank=True, default="")),
                ("destaque", models.BooleanField(default=False)),
                (
                    "classificacao",
                    models.IntegerField(
                        choices=[
                            (1, "★"),
                            (2, "★★"),
                            (3, "★★★"),
                            (4, "★★★★"),
                            (5, "★★★★★"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="tfcs", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sigla", models.CharField(blank=True, max_length=20)),
                ("codigo", models.CharField(blank=True, max_length=20)),
                ("ects", models.IntegerField()),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField(default=1)),
                ("natureza", models.CharField(blank=True, max_length=50)),
                ("lingua", models.CharField(blank=True, max_length=50)),
                ("objetivos", models.TextField(blank=True)),
                ("programa", models.TextField(blank=True)),
                ("metodologia", models.TextField(blank=True)),
                ("bibliografia", models.TextField(blank=True)),
                ("imagem", models.ImageField(blank=True, upload_to="ucs/")),
                (
                    "docentes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="unidades_curriculares",
                        to="portfolio.docente",
                    ),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades_curriculares",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projeto",
            name="unidade_curricular",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projetos",
                to="portfolio.unidadecurricular",
            ),
        ),
        migrations.CreateModel(
            name="UsoIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ferramenta", models.CharField(max_length=100)),
                ("descricao_uso", models.TextField()),
                ("contribuicao", models.TextField()),
                ("data", models.DateField()),
                (
                    "making_of",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usos_ia",
                        to="portfolio.makingof",
                    ),
                ),
            ],
        ),
    ]
