# Generated by Django 6.0.3 on 2026-03-31 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("pagina_lusofona", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sigla", models.CharField(max_length=10)),
                ("ects_totais", models.IntegerField()),
                ("duracao_anos", models.IntegerField()),
                (
                    "regime",
                    models.CharField(
                        choices=[
                            ("presencial", "Presencial"),
                            ("elearning", "E-Learning"),
                            ("misto", "Misto"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sigla", models.CharField(max_length=10)),
                ("ects", models.IntegerField()),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("descricao", models.TextField(blank=True)),
                ("imagem", models.ImageField(blank=True, upload_to="ucs/")),
                (
                    "docentes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="unidades_curriculares",
                        to="licenciatura.docente",
                    ),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades_curriculares",
                        to="licenciatura.licenciatura",
                    ),
                ),
            ],
        ),
    ]
