# Generated by Django 6.0.3 on 2026-04-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenciatura", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="descricao",
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="bibliografia",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="codigo",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="lingua",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="metodologia",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="natureza",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="objetivos",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="programa",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="docente",
            name="email",
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="semestre",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="sigla",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
