# Generated by Django 6.0.3 on 2026-03-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("linguagem", "Linguagem"),
                            ("framework", "Framework"),
                            ("base_dados", "Base de Dados"),
                            ("devops", "DevOps"),
                            ("ferramenta", "Ferramenta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("logo", models.ImageField(blank=True, upload_to="tecnologias/")),
                ("website", models.URLField(blank=True)),
                (
                    "nivel_interesse",
                    models.IntegerField(
                        choices=[
                            (1, "Iniciante"),
                            (2, "Básico"),
                            (3, "Intermédio"),
                            (4, "Avançado"),
                            (5, "Especialista"),
                        ],
                        default=3,
                    ),
                ),
                ("destaque", models.TextField(blank=True)),
            ],
        ),
    ]
